Final, little adjustments

diff --git a/pipeline/ci/sign-pipeline/cosign/cosign-sign.yml b/pipeline/ci/sign-pipeline/cosign/cosign-sign.yml
--- a/pipeline/ci/sign-pipeline/cosign/cosign-sign.yml
+++ b/pipeline/ci/sign-pipeline/cosign/cosign-sign.yml
@@ -1,14 +1,16 @@
 default:
   image: quay.io/bastiaanvanderbijl/docker:26.1.3
 
-verify-image-before-push:
-  stage: sign-pipeline:verify-image
+sign-image:
+  stage: sign-pipeline:sign-image
+  needs:
+    - push-image
   services:
     - name: quay.io/bastiaanvanderbijl/docker:26.1.3-dind
       command: ["--insecure-registry=172.20.0.2:5000"]
-      alias: docker-dind-verify-image
+      alias: docker-dind-sign-image
   variables:
-    DOCKER_HOST: tcp://docker-dind-verify-image:2375/
+    DOCKER_HOST: tcp://docker-dind-sign-image:2375/
     COSIGN_TLOG_UPLOAD: "y"
   script:
     # Install necessary tools
@@ -27,23 +29,31 @@ verify-image-before-push:
     - chmod +x cosign
     - mv cosign /usr/local/bin/
     
-    # Authenticate with Vault for public key
+    # Extract image name from the full path
+    - export IMAGE_ONLY_NAME=$(echo $IMAGE_NAME | awk -F/ '{print $NF}')
+    - echo $IMAGE_ONLY_NAME
+
+    - export FINAL_IMAGE=172.20.0.2:5000/${IMAGE_ONLY_NAME}:${IMAGE_TAG}
+
+    # Sign image
+
+    # Authenticate with Vault for private key
     - export VAULT_ADDR=$VAULT_ADDR
-    - export VAULT_TOKEN=$VAULT_TOKEN_PUBLIC_KEY
+    - export VAULT_TOKEN=$VAULT_TOKEN_PRIVATE_KEY
+    - export COSIGN_PASSWORD=$COSIGN_PASSWORD
 
-    # Verify Image
-
-    # Retrieve the public key from Vault
-    - if ! vault kv get -format=json public_keys/${TOKEN_PATH} | jq -r .data.key > cosign.pub; then
-        echo "Failed to retrieve or No public key found in ${TOKEN_PATH} for ${IMAGE_NAME}:${IMAGE_TAG}. Check if public key is present." >&2;
+    # Retrieve the private key from Vault
+    - if ! vault kv get -format=json private_key/test | jq -r .data.key > cosign.key; then
+        echo "Failed to retrieve or No private key found in ${TOKEN_PATH}. Check if private key is present." >&2;
         exit 1;
       fi
-
-    # Verify the container image with Cosign
-    - if ! cosign verify --key cosign.pub $IMAGE_NAME:$IMAGE_TAG; then
-        echo "Container image has been tampered with or wrong public key used." >&2;
+    
+    # Sign the container image with Cosign using the digest
+    - if ! cosign sign --key cosign.key ${FINAL_IMAGE}; then
+        echo "Failed to sign the container image." >&2;
         exit 1;
       fi
+    # Push the signed image to the local registry
   allow_failure: false
   rules:
     - if: '$CI_COMMIT_TAG == "sign-pipeline"'
